/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    'personal-information': PersonalInformation;
    'profile-photo': ProfilePhoto;
    business: Business;
    'supporting-documents': SupportingDocument;
    'business-permits': BusinessPermit;
    requests: Request;
    households: Household;
    reports: Report;
    media: Media;
    users: User;
    posts: Post;
    financing: Financing;
    'financing-audit-log': FinancingAuditLog;
    'storage-folders': StorageFolder;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'personal-information': PersonalInformationSelect<false> | PersonalInformationSelect<true>;
    'profile-photo': ProfilePhotoSelect<false> | ProfilePhotoSelect<true>;
    business: BusinessSelect<false> | BusinessSelect<true>;
    'supporting-documents': SupportingDocumentsSelect<false> | SupportingDocumentsSelect<true>;
    'business-permits': BusinessPermitsSelect<false> | BusinessPermitsSelect<true>;
    requests: RequestsSelect<false> | RequestsSelect<true>;
    households: HouseholdsSelect<false> | HouseholdsSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    financing: FinancingSelect<false> | FinancingSelect<true>;
    'financing-audit-log': FinancingAuditLogSelect<false> | FinancingAuditLogSelect<true>;
    'storage-folders': StorageFoldersSelect<false> | StorageFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'theme-settings': ThemeSetting;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'theme-settings': ThemeSettingsSelect<false> | ThemeSettingsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personal-information".
 */
export interface PersonalInformation {
  id: number;
  photo?: (number | null) | ProfilePhoto;
  name: {
    firstName: string;
    middleName?: string | null;
    lastName: string;
    fullName?: string | null;
  };
  contact?: {
    emailAddress?: string | null;
    localAddress?: string | null;
  };
  demographics?: {
    sex?: ('male' | 'female' | 'other') | null;
    birthDate?: string | null;
    maritalStatus?: ('single' | 'married' | 'divorced' | 'widowed') | null;
  };
  status?: {
    residencyStatus?: ('renting' | 'own-mortgage' | 'own-outright') | null;
    lifeStatus?: ('alive' | 'deceased') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile-photo".
 */
export interface ProfilePhoto {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business".
 */
export interface Business {
  id: number;
  businessName: string;
  address: string;
  registrationDate: string;
  typeOfOwnership: 'sole proprietorship' | 'partnership' | 'corporation' | 'llc';
  owners?:
    | {
        ownerName: string;
        id?: string | null;
      }[]
    | null;
  typeOfCorporation?: ('public' | 'private' | 'non-profit') | null;
  businessContactNo?: string | null;
  businessEmailAddress: string;
  supportingDocuments?: (number | SupportingDocument)[] | null;
  status?: ('active' | 'inactive' | 'pending') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supporting-documents".
 */
export interface SupportingDocument {
  id: number;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-permits".
 */
export interface BusinessPermit {
  id: number;
  business: number | Business;
  validity: string;
  officialReceiptNo: string;
  issuedTo: string;
  amount: number;
  supportingDocuments?: (number | SupportingDocument)[] | null;
  paymentDate?: string | null;
  status?: ('pending' | 'approved' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requests".
 */
export interface Request {
  id: number;
  type: 'indigencyCertificate' | 'barangayClearance' | 'barangayResidency';
  person: number | PersonalInformation;
  purpose?: string | null;
  additionalInformation?: {
    forWhom?: string | null;
    remarks?: string | null;
    duration?: string | null;
  };
  supportingDocuments?: (number | SupportingDocument)[] | null;
  status?: ('pending' | 'processing' | 'approved' | 'rejected' | 'completed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "households".
 */
export interface Household {
  id: number;
  familyName: string;
  members?:
    | {
        member?: (number | null) | PersonalInformation;
        id?: string | null;
      }[]
    | null;
  localAddress: string;
  status: 'active' | 'inactive';
  residencyDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: number;
  title: string;
  date: string;
  description: string;
  location: string;
  involvedPersons?:
    | {
        name: string;
        role: 'complainant' | 'respondent' | 'witness' | 'other';
        statement?: string | null;
        personalInfo?: (number | null) | PersonalInformation;
        id?: string | null;
      }[]
    | null;
  supportingDocuments?: (number | SupportingDocument)[] | null;
  reportStatus?: ('open' | 'inProgress' | 'closed') | null;
  submittedBy: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'staff' | 'citizen';
  personalInfo?: (number | null) | PersonalInformation;
  isActive?: ('active' | 'inactive') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  folder?: (number | null) | StorageFolder;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storage-folders".
 */
export interface StorageFolder {
  id: number;
  name: string;
  parent?: (number | null) | StorageFolder;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  author: number | User;
  content: string;
  slug?: string | null;
  publishedDate: string;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financing".
 */
export interface Financing {
  id: number;
  title: string;
  description?: string | null;
  approvalState?: ('draft' | 'submitted' | 'under_review' | 'approved' | 'rejected') | null;
  accountType?: ('capital' | 'operational' | 'grant' | 'revenue' | 'transfer') | null;
  fiscalYear?: string | null;
  budgetedAmount?: number | null;
  /**
   * Reference to budget allocation or code
   */
  budgetReference?: string | null;
  departmentCode?: string | null;
  /**
   * Justification for this expenditure
   */
  justification?: string | null;
  /**
   * Legislative or policy authorization reference
   */
  authorizationReference?: string | null;
  approvalHistory?:
    | {
        state: 'draft' | 'submitted' | 'under_review' | 'approved' | 'rejected';
        timestamp: string;
        user: string;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  groups?:
    | {
        title: string;
        description?: string | null;
        subtotalOperation?: ('sum' | 'average' | 'min' | 'max') | null;
        items?:
          | {
              number?: number | null;
              title?: string | null;
              value?: number | null;
              operation?: ('add' | 'subtract' | 'multiply' | 'divide') | null;
              /**
               * Government accounting code
               */
              accountCode?: string | null;
              /**
               * Fiscal period (e.g., Q1 2023)
               */
              fiscalPeriod?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  finalCalculations?:
    | {
        number?: number | null;
        title?: string | null;
        operation?: ('add' | 'subtract' | 'multiply' | 'divide' | 'groupRef') | null;
        value?: number | null;
        /**
         * Zero-based index of the group
         */
        groupReference?: number | null;
        id?: string | null;
      }[]
    | null;
  auditTrail?:
    | {
        action: string;
        timestamp: string;
        user: string;
        changes?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Audit trail for all financing record changes
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financing-audit-log".
 */
export interface FinancingAuditLog {
  id: number;
  timestamp: string;
  user: number | User;
  action: 'create' | 'update' | 'delete' | 'state_change';
  record: number | Financing;
  /**
   * Stored for reference even if the record is deleted
   */
  financingTitle?: string | null;
  previousState?: ('draft' | 'submitted' | 'under_review' | 'approved' | 'rejected') | null;
  newState?: ('draft' | 'submitted' | 'under_review' | 'approved' | 'rejected') | null;
  /**
   * Detailed changes made to the record
   */
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Additional context about this change
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'personal-information';
        value: number | PersonalInformation;
      } | null)
    | ({
        relationTo: 'profile-photo';
        value: number | ProfilePhoto;
      } | null)
    | ({
        relationTo: 'business';
        value: number | Business;
      } | null)
    | ({
        relationTo: 'supporting-documents';
        value: number | SupportingDocument;
      } | null)
    | ({
        relationTo: 'business-permits';
        value: number | BusinessPermit;
      } | null)
    | ({
        relationTo: 'requests';
        value: number | Request;
      } | null)
    | ({
        relationTo: 'households';
        value: number | Household;
      } | null)
    | ({
        relationTo: 'reports';
        value: number | Report;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'financing';
        value: number | Financing;
      } | null)
    | ({
        relationTo: 'financing-audit-log';
        value: number | FinancingAuditLog;
      } | null)
    | ({
        relationTo: 'storage-folders';
        value: number | StorageFolder;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personal-information_select".
 */
export interface PersonalInformationSelect<T extends boolean = true> {
  photo?: T;
  name?:
    | T
    | {
        firstName?: T;
        middleName?: T;
        lastName?: T;
        fullName?: T;
      };
  contact?:
    | T
    | {
        emailAddress?: T;
        localAddress?: T;
      };
  demographics?:
    | T
    | {
        sex?: T;
        birthDate?: T;
        maritalStatus?: T;
      };
  status?:
    | T
    | {
        residencyStatus?: T;
        lifeStatus?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile-photo_select".
 */
export interface ProfilePhotoSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business_select".
 */
export interface BusinessSelect<T extends boolean = true> {
  businessName?: T;
  address?: T;
  registrationDate?: T;
  typeOfOwnership?: T;
  owners?:
    | T
    | {
        ownerName?: T;
        id?: T;
      };
  typeOfCorporation?: T;
  businessContactNo?: T;
  businessEmailAddress?: T;
  supportingDocuments?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supporting-documents_select".
 */
export interface SupportingDocumentsSelect<T extends boolean = true> {
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-permits_select".
 */
export interface BusinessPermitsSelect<T extends boolean = true> {
  business?: T;
  validity?: T;
  officialReceiptNo?: T;
  issuedTo?: T;
  amount?: T;
  supportingDocuments?: T;
  paymentDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requests_select".
 */
export interface RequestsSelect<T extends boolean = true> {
  type?: T;
  person?: T;
  purpose?: T;
  additionalInformation?:
    | T
    | {
        forWhom?: T;
        remarks?: T;
        duration?: T;
      };
  supportingDocuments?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "households_select".
 */
export interface HouseholdsSelect<T extends boolean = true> {
  familyName?: T;
  members?:
    | T
    | {
        member?: T;
        id?: T;
      };
  localAddress?: T;
  status?: T;
  residencyDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  description?: T;
  location?: T;
  involvedPersons?:
    | T
    | {
        name?: T;
        role?: T;
        statement?: T;
        personalInfo?: T;
        id?: T;
      };
  supportingDocuments?: T;
  reportStatus?: T;
  submittedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  personalInfo?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  author?: T;
  content?: T;
  slug?: T;
  publishedDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financing_select".
 */
export interface FinancingSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  approvalState?: T;
  accountType?: T;
  fiscalYear?: T;
  budgetedAmount?: T;
  budgetReference?: T;
  departmentCode?: T;
  justification?: T;
  authorizationReference?: T;
  approvalHistory?:
    | T
    | {
        state?: T;
        timestamp?: T;
        user?: T;
        notes?: T;
        id?: T;
      };
  groups?:
    | T
    | {
        title?: T;
        description?: T;
        subtotalOperation?: T;
        items?:
          | T
          | {
              number?: T;
              title?: T;
              value?: T;
              operation?: T;
              accountCode?: T;
              fiscalPeriod?: T;
              id?: T;
            };
        id?: T;
      };
  finalCalculations?:
    | T
    | {
        number?: T;
        title?: T;
        operation?: T;
        value?: T;
        groupReference?: T;
        id?: T;
      };
  auditTrail?:
    | T
    | {
        action?: T;
        timestamp?: T;
        user?: T;
        changes?: T;
        id?: T;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financing-audit-log_select".
 */
export interface FinancingAuditLogSelect<T extends boolean = true> {
  timestamp?: T;
  user?: T;
  action?: T;
  record?: T;
  financingTitle?: T;
  previousState?: T;
  newState?: T;
  changes?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storage-folders_select".
 */
export interface StorageFoldersSelect<T extends boolean = true> {
  name?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings".
 */
export interface ThemeSetting {
  id: number;
  background?: string | null;
  foreground?: string | null;
  card?: string | null;
  cardForeground?: string | null;
  popover?: string | null;
  popoverForeground?: string | null;
  primary?: string | null;
  primaryForeground?: string | null;
  secondary?: string | null;
  secondaryForeground?: string | null;
  muted?: string | null;
  mutedForeground?: string | null;
  accent?: string | null;
  accentForeground?: string | null;
  destructive?: string | null;
  destructiveForeground?: string | null;
  border?: string | null;
  input?: string | null;
  ring?: string | null;
  sidebarBackground?: string | null;
  sidebarForeground?: string | null;
  sidebarPrimary?: string | null;
  sidebarPrimaryForeground?: string | null;
  sidebarAccent?: string | null;
  sidebarAccentForeground?: string | null;
  sidebarBorder?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  heroImage?: (number | null) | Media;
  authImage?: (number | null) | Media;
  logo: number | Media;
  favicon?: (number | null) | Media;
  description?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  address?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings_select".
 */
export interface ThemeSettingsSelect<T extends boolean = true> {
  background?: T;
  foreground?: T;
  card?: T;
  cardForeground?: T;
  popover?: T;
  popoverForeground?: T;
  primary?: T;
  primaryForeground?: T;
  secondary?: T;
  secondaryForeground?: T;
  muted?: T;
  mutedForeground?: T;
  accent?: T;
  accentForeground?: T;
  destructive?: T;
  destructiveForeground?: T;
  border?: T;
  input?: T;
  ring?: T;
  sidebarBackground?: T;
  sidebarForeground?: T;
  sidebarPrimary?: T;
  sidebarPrimaryForeground?: T;
  sidebarAccent?: T;
  sidebarAccentForeground?: T;
  sidebarBorder?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  heroImage?: T;
  authImage?: T;
  logo?: T;
  favicon?: T;
  description?: T;
  contactEmail?: T;
  contactPhone?: T;
  address?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}